//
//  HomeProtocols.swift
//  AppMovies
//
//  Created Roberto Antonio Alba Hernández on 18/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeWireframeProtocol: AnyObject {
    func goToShowTV(showTV : Result)
    func showProfile()
    func closeSession()
}
//MARK: Presenter -
protocol HomePresenterProtocol: AnyObject {
    func getPopularShows(completion: @escaping ((ShowsTV?) -> ()))
    func getShowsTV(completion: @escaping (([ShowsTV?]) -> ()))
    func goToShowTV(showTV : Result)
    func logOut(completion:@escaping((_ response:Bool)->()))
    func showProfile()
    func closeSession()
}

//MARK: Interactor -
protocol HomeInteractorProtocol: AnyObject {
    var presenter: HomePresenterProtocol?  { get set }
    func getPopularShows(completion: @escaping ((ShowsTV?) -> ()))
    func getShowsTV(completion: @escaping (([ShowsTV?]) -> ()))
    func logOut(completion:@escaping((_ response:Bool)->()))
}

//MARK: View -
protocol HomeViewProtocol: AnyObject {

  var presenter: HomePresenterProtocol?  { get set }
}
