//
//  HomeRouter.swift
//  AppMovies
//
//  Created Roberto Antonio Alba Hernández on 18/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeRouter: HomeWireframeProtocol {
    
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = HomeViewController(nibName: nil, bundle: nil)
        let interactor = HomeInteractor()
        let router = HomeRouter()
        let presenter = HomePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func goToShowTV(showTV: Result) {
        let detailsShowTVController = DetailsShowTVRouter.createModule(showTV: showTV)
        
        self.viewController?.navigationController?.pushViewController(detailsShowTVController, animated: true)
    }
    
    func showProfile() {
        let profileController = ProfileRouter.createModule()
//        profileController.modalPresentationStyle = .currentContext
        viewController?.navigationController?.present(profileController, animated: true)
    }
    
    func closeSession() {
        self.viewController?.dismiss(animated: true)
    }
}
