//
//  AuthenticateViewController.swift
//  AppMovies
//
//  Created Roberto Antonio Alba Hernández on 17/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import WebKit


class AuthenticateViewController: UIViewController, AuthenticateViewProtocol {

	var presenter: AuthenticatePresenterProtocol?
    var requeestToken: String?
    var completion:  ((Bool) -> ())?
    
    
    let webView : WKWebView = {
        let view = WKWebView()
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()

	override func viewDidLoad() {
        super.viewDidLoad()
        
        let url:String = "https://www.themoviedb.org/authenticate/\(requeestToken ?? "")"
        
        let request = URLRequest(url: URL(string: url)!)
        webView.load(request)
        
        setupView()
    }
    
    func setupView()  {
    
        self.view.addSubview(webView)
        webView.navigationDelegate = self
        
        webView.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor).isActive = true
        webView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor).isActive = true
        webView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor).isActive = true
        webView.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor).isActive = true
            
    }
}

extension AuthenticateViewController : WKNavigationDelegate {
    
    func webView(_ webView: WKWebView, didReceiveServerRedirectForProvisionalNavigation navigation: WKNavigation!) {
        if let url = webView.url?.absoluteString{
            print("url = \(url)")
            
            completion?(true)
        }
    }
}
