//
//  AuthenticateProtocols.swift
//  AppMovies
//
//  Created Roberto Antonio Alba Hernández on 17/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol AuthenticateWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol AuthenticatePresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol AuthenticateInteractorProtocol: AnyObject {

  var presenter: AuthenticatePresenterProtocol?  { get set }
}

//MARK: View -
protocol AuthenticateViewProtocol: AnyObject {

  var presenter: AuthenticatePresenterProtocol?  { get set }
}
