//
//  AuthenticateRouter.swift
//  AppMovies
//
//  Created Roberto Antonio Alba Hernández on 17/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AuthenticateRouter: AuthenticateWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(requestToken: String, completion: @escaping ((Bool) -> ())) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = AuthenticateViewController(nibName: nil, bundle: nil)
        let interactor = AuthenticateInteractor()
        let router = AuthenticateRouter()
        let presenter = AuthenticatePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        view.requeestToken = requestToken
        view.completion = completion
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
