//
//  AuthenticateInteractor.swift
//  AppMovies
//
//  Created Roberto Antonio Alba Hernández on 17/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AuthenticateInteractor: AuthenticateInteractorProtocol {

    weak var presenter: AuthenticatePresenterProtocol?
}
