//
//  AuthenticatePresenter.swift
//  AppMovies
//
//  Created Roberto Antonio Alba Hernández on 17/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AuthenticatePresenter: AuthenticatePresenterProtocol {

    weak private var view: AuthenticateViewProtocol?
    var interactor: AuthenticateInteractorProtocol?
    private let router: AuthenticateWireframeProtocol

    init(interface: AuthenticateViewProtocol, interactor: AuthenticateInteractorProtocol?, router: AuthenticateWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
