//
//  LoginRouter.swift
//  AppMovies
//
//  Created Roberto Antonio Alba Hernández on 17/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginRouter: LoginWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LoginViewController(nibName: nil, bundle: nil)
        let interactor = LoginInteractor()
        let router = LoginRouter()
        let presenter = LoginPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func goToAuthenticate(requestToken: String, completion: @escaping ((Bool) -> ())) {
        let authenticateController = AuthenticateRouter.createModule(requestToken: requestToken, completion: completion)
        authenticateController.modalPresentationStyle = .fullScreen
        viewController?.present(authenticateController, animated: true)
        
    }
    
    func goToHome() {
        let homeContoller = HomeRouter.createModule()
        
        let navController = UINavigationController(rootViewController: homeContoller)
        
        navController.modalPresentationStyle = .fullScreen
        viewController?.present(navController, animated: true)
        
    }
}
