//
//  LoginProtocols.swift
//  AppMovies
//
//  Created Roberto Antonio Alba Hernández on 17/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LoginWireframeProtocol: AnyObject {
    func goToAuthenticate(requestToken:String,completion:@escaping((_ response:Bool)->()))
    func goToHome()
}
//MARK: Presenter -
protocol LoginPresenterProtocol: AnyObject {
    
    func getRequestToken(completion:@escaping((_ response:Bool, _ error:String)->()))
    func setRequestToken(requestToken : RequestToken, andSession session : Session)
    func authenticate(completion:@escaping((_ response:Bool)->()))
    func validateLogin(withUserName userName:String, andPassword pasword:String, completion:@escaping((_ response:Bool, _ error:String)->()))
    func getRequestToken()->String
    func goToHome()
}

//MARK: Interactor -
protocol LoginInteractorProtocol: AnyObject {
    var presenter: LoginPresenterProtocol?  { get set }
    func getRequestToken(completion:@escaping((_ response:Bool, _ error:String)->()))
    func validateLogin(withUserName userName:String, andPassword pasword:String, completion:@escaping((_ response:Bool, _ error:String)->()))
}

//MARK: View -
protocol LoginViewProtocol: AnyObject {
    var presenter: LoginPresenterProtocol?  { get set }
}
