//
//  ProfileViewController.swift
//  AppMovies
//
//  Created Roberto Antonio Alba Hernández on 19/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileViewController: UIViewController, ProfileViewProtocol {

	var presenter: ProfilePresenterProtocol?
    var showsTV : [Result]?
    var profile : Profile!

    var scrollView:UIScrollView!
    var collectionView : UICollectionView!
    
    let labelTitle: UILabel = {
        let view = UILabel()
        view.text = "Profile"
        view.font = UIFont.systemFont(ofSize: 30)
        view.textColor = UIColor(red: 29/255.0, green: 180/255.0, blue: 93/255.0, alpha: 1.0)
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()
    
    let imageView: CustomImageView = {
        let view = CustomImageView()
        view.image = UIImage(named: "logo")
        view.layer.cornerRadius = 60
        view.layer.masksToBounds = true
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()
    
    let labelUserName: UILabel = {
        let view = UILabel()
        view.font = UIFont.systemFont(ofSize: 18)
        view.textColor = UIColor(red: 29/255.0, green: 180/255.0, blue: 93/255.0, alpha: 1.0)
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()
    
    let labelFavorites: UILabel = {
        let view = UILabel()
        view.text = "Favorite Shows"
        view.font = UIFont.systemFont(ofSize: 25)
        view.textColor = UIColor(red: 29/255.0, green: 180/255.0, blue: 93/255.0, alpha: 1.0)
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()
    
    
	override func viewDidLoad() {
        super.viewDidLoad()
        
        self.navigationItem.title = ""
        self.navigationController?.navigationBar.tintColor = UIColor(red: 250/255.0, green: 250/255.0, blue: 250/255.0, alpha: 1.0)
        
//        self.view.backgroundColor = UIColor(red: 21/255.0, green: 39/255.0, blue: 46/255.0, alpha: 1.0)
        
        self.view.backgroundColor = UIColor(red: 9/255.0, green: 22/255.0, blue: 26/255.0, alpha: 1.0)
        
        self.navigationController?.navigationBar.backgroundColor = UIColor(red: 46/255.0, green: 55/255.0, blue: 58/255.0, alpha: 1.0)
                
        self.navigationController?.navigationBar.titleTextAttributes = [NSAttributedString.Key.font:UIFont.systemFont(ofSize: 18),NSAttributedString.Key.foregroundColor:UIColor(red: 250/255.0, green: 250/255.0, blue: 250/255.0, alpha: 1.0),NSAttributedString.Key.kern : -0.43]
        
        let window = UIApplication.shared.windows.filter {$0.isKeyWindow}.first
        let statusBar = UIView(frame: window?.windowScene?.statusBarManager?.statusBarFrame ?? CGRect.zero)
        statusBar.backgroundColor = UIColor(red: 46/255.0, green: 55/255.0, blue: 58/255.0, alpha: 1.0)
        window?.addSubview(statusBar)
                
        
        presenter?.getInfoProfile(completion: { [weak self] (object: Profile?) in
            if let object = object {
                self?.profile = object
                self?.setupView()
                
                self?.showsTV = self?.presenter?.getFavorites()
                
                self?.collectionView.reloadData()
            }
        })
        
        
    }
    
    func setupView() {
        scrollView = UIScrollView()
        scrollView.showsVerticalScrollIndicator = true
        self.view.addSubview(scrollView)
        
        scrollView.addSubview(labelTitle)
        labelTitle.topAnchor.constraint(equalTo: scrollView.topAnchor, constant: 50).isActive = true
        labelTitle.leadingAnchor.constraint(equalTo: scrollView.leadingAnchor, constant: 20).isActive = true
        
        
        scrollView.addSubview(imageView)
        imageView.topAnchor.constraint(equalTo: scrollView.topAnchor, constant: 120).isActive = true
        imageView.leadingAnchor.constraint(equalTo: scrollView.leadingAnchor, constant: 30).isActive = true
        imageView.heightAnchor.constraint(equalToConstant: 120).isActive = true
        imageView.widthAnchor.constraint(equalToConstant: 120).isActive = true
        
        imageView.loadImageUsingUrlString(urlString: profile.avatar.gravatar.hash, isAvatar: true)
        
        scrollView.addSubview(labelUserName)
        labelUserName.centerYAnchor.constraint(equalTo: imageView.centerYAnchor, constant: 0).isActive = true
        labelUserName.leadingAnchor.constraint(equalTo: imageView.trailingAnchor, constant: 25).isActive = true
        labelUserName.text = profile.username
        
        scrollView.addSubview(labelFavorites)
        labelFavorites.topAnchor.constraint(equalTo: imageView.bottomAnchor, constant: 100).isActive = true
        labelFavorites.leadingAnchor.constraint(equalTo: scrollView.leadingAnchor, constant: 20).isActive = true
        labelFavorites.heightAnchor.constraint(equalToConstant: 20).isActive = true
        
        let layout = UICollectionViewFlowLayout()
        layout.scrollDirection = .horizontal
        layout.minimumLineSpacing = 15
        layout.minimumInteritemSpacing = 0
        collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
        collectionView.isPagingEnabled = true
        collectionView.backgroundColor = .clear
        collectionView.contentInset = UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0)
        collectionView.scrollIndicatorInsets = UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0)
        
        collectionView.register(MovieCell.self, forCellWithReuseIdentifier: "\(MovieCell.self)")

        collectionView.dataSource = self
        collectionView.delegate = self
        
        
        scrollView.addSubview(collectionView)
        collectionView.translatesAutoresizingMaskIntoConstraints = false
        collectionView.topAnchor.constraint(equalTo: imageView.bottomAnchor, constant: 155).isActive = true
        collectionView.leadingAnchor.constraint(equalTo: scrollView.leadingAnchor, constant: 0).isActive = true
        collectionView.trailingAnchor.constraint(equalTo: scrollView.trailingAnchor, constant: 0).isActive = true
        collectionView.widthAnchor.constraint(equalTo: scrollView.widthAnchor, multiplier: 1.0).isActive = true
        collectionView.heightAnchor.constraint(equalToConstant: 350).isActive = true
        
        
        
        scrollView.translatesAutoresizingMaskIntoConstraints = false
        scrollView.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor).isActive = true
        scrollView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor).isActive = true
        scrollView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor).isActive = true
        scrollView.widthAnchor.constraint(equalTo: self.view.widthAnchor).isActive = true
        scrollView.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor).isActive = true
    }

}

extension ProfileViewController : UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return showsTV?.count ?? 0
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "\(MovieCell.self)", for: indexPath) as? MovieCell else {
            return UICollectionViewCell()
        }
        
        if let showTV = showsTV?[indexPath.row] {
            cell.configureCell(result: showTV)
        }
        
        cell.backgroundColor = UIColor(red: 21/255.0, green: 39/255.0, blue: 46/255.0, alpha: 1.0)
        
        cell.layer.cornerRadius = 15.0
        cell.layer.masksToBounds = true
        
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize(width: (collectionView.frame.width - 15) / 2, height: 350)
    }
    
}
