//
//  ProfileInteractor.swift
//  AppMovies
//
//  Created Roberto Antonio Alba Hernández on 19/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import CoreData

class ProfileInteractor: ProfileInteractorProtocol {
    weak var presenter: ProfilePresenterProtocol?
    
    func getInfoProfile(completion: @escaping ((Profile?) -> ())) {
        
        let params = ["api_key":"\(APIManager.API_KEY)", "session_id":"\(APIManager.session?.session_id ?? "")"]
        
        APIManager.fetchObject(apiURL: APIURL.PROFILE, parameters: params) { (object: Profile? , error: APIError?) in
            
            if let object = object {
                completion(object)
            } else {
                completion(nil)
            }
        }
    }
    
    func getFavorites() -> [Result]? {
        let appDelegate = UIApplication.shared.delegate as! AppDelegate
        let context = appDelegate.persistentContainer.viewContext
        
        var showsTV: [Result] = [Result]()
        
        let fetchRequest: NSFetchRequest<Favorite> = Favorite.fetchRequest()
        
        do {
//            fetchRequest.predicate = NSPredicate(format: "idShow == %d", idShowTV)
            let fetchedResults = try context.fetch(fetchRequest)
            
            for item in fetchedResults {
                var showTV = Result()
                showTV.id = Int(item.idShow)
                showTV.name = item.name
                showTV.voteAverage = item.voteAverage
                showTV.firstAirDate = item.firstAirDate
                showTV.overview = item.overview
                showTV.posterPath = item.posterPath
                
                showsTV.append(showTV)
            }
            
            return showsTV
            
        } catch {
            print("Unable to Fetch Workouts, (\(error))")
//            return false
            return showsTV
        }
    }
}
