//
//  ProfileInteractor.swift
//  AppMovies
//
//  Created Roberto Antonio Alba Hernández on 19/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileInteractor: ProfileInteractorProtocol {
    weak var presenter: ProfilePresenterProtocol?
    
    func getInfoProfile(completion: @escaping ((Profile?) -> ())) {
        
        let params = ["api_key":"\(APIManager.API_KEY)", "session_id":"\(APIManager.session?.session_id ?? "")"]
        
        APIManager.fetchObject(apiURL: APIURL.PROFILE, parameters: params) { (object: Profile? , error: APIError?) in
            
            if let object = object {
                completion(object)
            } else {
                completion(nil)
            }
        }
    }
}
