//
//  DetailsShowTVProtocols.swift
//  AppMovies
//
//  Created Roberto Antonio Alba Hernández on 19/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DetailsShowTVWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol DetailsShowTVPresenterProtocol: AnyObject {
    func getProviders(idShowTV: Int?, completion: @escaping ((WatchTVProviders?) -> ()))
    func getProviders(idShowTV: Int?,completionHandler:@escaping (_ objects: [String : AnyObject]?, _ error: APIError?)->Void)
    func getGenres(genresIds:[Int]) -> String
    func getCountries(originCountry:[String]) -> String
}

//MARK: Interactor -
protocol DetailsShowTVInteractorProtocol: AnyObject {
    var presenter: DetailsShowTVPresenterProtocol?  { get set }
    func getProviders(idShowTV: Int?, completion: @escaping ((WatchTVProviders?) -> ()))
    func getProviders(idShowTV: Int?,completionHandler:@escaping (_ objects: [String : AnyObject]?, _ error: APIError?)->Void)
}

//MARK: View -
protocol DetailsShowTVViewProtocol: AnyObject {

  var presenter: DetailsShowTVPresenterProtocol?  { get set }
}
